### ISSUE TITLE
"important" addon will *always* add !important, even if the style already has it

### ISSUE THREAD

**Issue by TheBosZ** [streamich/nano-css#196]
This:
```javascript
nano.sheet({
  'picker': {
    'z-index': '99999 !important',
 }
});
```
Gets turned into this:
```css
.__1m4gp78-picker {
  z-index:99999 !important !important;
}
```
Which is not valid.
