### ISSUE TITLE
"important" addon adds double "!important"

### ISSUE THREAD

**Issue by TheBosZ** [streamich/nano-css#198]
With the fix for #196, now the stylesheet gets generated with extra "!important" lines:

```css
.__sjcenb-data-fields {
    min-height:88px !important; !important;
}
```

Luckily, the extra lines get dropped since they're invalid, but it's not ideal.
