### ISSUE TITLE
"content" styles aren't handled well

### ISSUE THREAD

**Issue by TheBosZ** [streamich/nano-css#204]
When I use "content" styles, the styles *have* to be surrounded by an extra pair of quotes or it'll get messed up.

An example original CSS:

```css
.divider {
  &:after {
    content: '|';
  }
}
```

Code:
```javascript
nano.rule({
  divider: {
    '&:after': {
      content: '|',
    },
  },
});
```

Resulting CSS:
```css
.__1elt25k-divider:after {
    content:|;
}
```

Notice that the quotes have been stripped from the content character. If I use a doubly-quoted string `content: '"|"',` it works just fine.

I'm not sure that this is a bug or more of a "I have to look out for content rules since they're special" thing.
