### ISSUE TITLE
You can't use virtual with keyframes

### ISSUE THREAD

**Issue by TheBosZ** [streamich/nano-css#209]
Virtual will murder keyframes.

The following:

```css
@keyframes sk-foldCubeAngle {
	0%, 10% {
		transform: perspective(140px) rotateX(-180deg);
		opacity: 0;
	}
	25%, 75% {
		transform: perspective(140px) rotateX(0deg);
		opacity: 1;
	}
	90%, 100% {
		transform: perspective(140px) rotateY(180deg);
		opacity: 0;
	}
}
```

Gets murdered into something like this:
```css
@keyframes sk-foldCubeAngle{._ne:before 0%,._ne:before  10%{transform:perspective(140px) rotateX(-180deg)}}@keyframes sk-foldCubeAngle{._nf:before 0%,._nf:before  10%{opacity:0}}@keyframes sk-foldCubeAngle{._ng:before 25%,._ng:before  75%{transform:perspective(140px) rotateX(0deg)}}@keyframes sk-foldCubeAngle{._nh:before 25%,._nh:before  75%{opacity:1}}@keyframes sk-foldCubeAngle{._ni:before 90%,._ni:before  100%{transform:perspective(140px) rotateY(180deg)}}@keyframes sk-foldCubeAngle{._nj:before 90%,._nj:before  100%{opacity:0}}._nk:before{transform-origin:100% 100%}._nl{transform:scale(1.1) rotateZ(90deg)}._nm:before{animation-delay:0.3s}._nn{transform:scale(1.1) rotateZ(180deg)}._no:before{animation-delay:0.6s}._np{transform:scale(1.1) rotateZ(270deg)}._nq:before{animation-delay:0.9s}
```

When it should really just be:
```css
@keyframes sk-foldCubeAngle{0%, 10%{transform:perspective(140px) rotateX(-180deg);opacity:0;}25%, 75%{transform:perspective(140px) rotateX(0deg);opacity:1;}90%, 100%{transform:perspective(140px) rotateY(180deg);opacity:0;}}
```
