### ISSUE TITLE
@font-face results to invalid CSS

### ISSUE THREAD

**Issue by MindaugasVarkalys** [streamich/nano-css#220]
I run the following code
```javascript
nano.global({
    '@font-face': {
        fontFamily: 'Panton Regular',
        src: 'url("/fonts/Panton-Regular.woff2") format("woff2")',
        fontWeight: 'normal',
        fontStyle: 'normal'
    }
});
```
and it results to this CSS which is invalid
```css
@font-face{
 {
    font-family:Panton Regular;
    src:url("/fonts/Panton-Regular.woff2") format("woff2");
    font-weight:normal;
    font-style:normal;
}
}
```
Valid CSS looks like this:
```css
@font-face
 {
    font-family:Panton Regular;
    src:url("/fonts/Panton-Regular.woff2") format("woff2");
    font-weight:normal;
    font-style:normal;
}
```
